Document: apache-activemq
Title: Debian apache-activemq Manual
Author: <insert document author here>
Abstract: This manual describes what apache-activemq is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/apache-activemq/apache-activemq.sgml.gz

Format: postscript
Files: /usr/share/doc/apache-activemq/apache-activemq.ps.gz

Format: text
Files: /usr/share/doc/apache-activemq/apache-activemq.text.gz

Format: HTML
Index: /usr/share/doc/apache-activemq/html/index.html
Files: /usr/share/doc/apache-activemq/html/*.html
